#****************************************************************************
#
# Makefile for tool
# henuyx
#
# 2015-06-19
# ftp-test
#
#****************************************************************************

.PHONY: all
all:
	$(MAKE) -f Makefile.ftp-test

.PHONY: clean
clean:
	$(MAKE) -f Makefile.ftp-test clean

.PHONY: cleanall
cleanall:
	$(MAKE) -f Makefile.ftp-test cleanall
