#****************************************************************************
#
# Makefile for delete share memory
# henuyx
# 2015-06-19
#
#****************************************************************************

CXX	:= g++

INC_HEAD:= -I"../include"
INC_SLIB:=
CXXFLAGS:= -Wall -fPIC -Wno-deprecated -g $(INC_HEAD) $(INC_SLIB)

BIN_PATH:= .

BIN = ftp-test

SOURCES = ftp-test.cpp
OBJECTS = $(SOURCES:.cpp=.o)

.PHONY: all
all:$(BIN)

$(BIN):$(OBJECTS)
	@$(CXX) -o $(BIN_PATH)/$@ $(OBJECTS) ../ftp/libFtpOp.a  ../tcp/client/libTcpClient.a

.PHONY: clean
clean:
	rm -f *.o *~

.PHONY: cleanall
cleanall:
	rm -f *.o *~ $(BIN_PATH)/$(BIN)
